application: dancingoggin
version: sprint2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: css

- url: /js
  static_dir: js
  
- url: /images
  static_dir: images
  
- url: /sass
  static_dir: sass
  
  
- url: /contact
  script: contact.app 
 
- url: /resources 
  script: resources.app 
  
- url: /(photos|dances)
  script: construction.app 
  
- url: /lessons
  script: lessons.app 
  
- url: /(adminLessons|deleteLessons)
  script: adminLessons.app  
  

  
  
- url: /login
  script: login.app

- url: /index
  script: main.cpp
 
- url: .*
  script: main.app

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest
